version: '3.9'

services:
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
      - ADMINER_DEFAULT_USERNAME=root
      - ADMINER_DEFAULT_PASSWORD=test123
    networks:
      - mynetwork
    deploy:
      mode: replicated
      replicas: 1

  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=test123
    networks:
      - mynetwork
    command: ["--server-id=100", "--log-bin=ON"]
    deploy:
      mode: replicated
      replicas: 2

networks:
  mynetwork:

